"""Campaign state models — shared between LangGraph and CrewAI."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class CampaignMode(StrEnum):
    LIGHT = "light"     # T0 only, single pass, ~5-10 min
    MEDIUM = "medium"   # T0-T1, depth 2, ~30-60 min
    DEEP = "deep"       # T0-T2/T3, depth 4, ~2-6 hrs
    MONITOR = "monitor" # re-run with diff against last run


class PhaseStatus(StrEnum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    SKIPPED = "skipped"
    FAILED = "failed"


class PhaseResult(BaseModel):
    phase_name: str
    status: PhaseStatus
    started_at: datetime | None = None
    completed_at: datetime | None = None
    findings_count: int = 0
    entities_discovered: int = 0
    tools_run: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    reflection_notes: str = ""
    llm_cost_usd: float = 0.0


class SuccessCriteria(BaseModel):
    min_subdomains: int = 0
    min_emails: int = 0
    min_cloud_assets: int = 0
    min_findings: int = 0
    requires_m365_recon: bool = False
    requires_aws_recon: bool = False
    requires_code_recon: bool = False


class PhasePlan(BaseModel):
    phase_name: str
    description: str
    tier: str
    agents: list[str] = Field(default_factory=list)
    tools: list[str] = Field(default_factory=list)
    success_criteria: SuccessCriteria = Field(default_factory=SuccessCriteria)
    kill_criteria: list[str] = Field(default_factory=list)
    time_budget_min: int = 30
    cost_budget_usd: float = 5.0
    depends_on: list[str] = Field(default_factory=list)


class CampaignPlan(BaseModel):
    campaign_id: str
    mode: CampaignMode
    phases: list[PhasePlan] = Field(default_factory=list)
    total_time_budget_min: int = 120
    total_cost_budget_usd: float = 50.0
    planner_notes: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


class CampaignState(BaseModel):
    """
    Mutable campaign state persisted across LangGraph phases.
    Serialized to/from SQLite checkpoint.
    """

    campaign_id: str
    engagement_id: str
    mode: CampaignMode
    scope_hash: str
    seeds: list[str] = Field(default_factory=list)  # initial target inputs

    # Phase tracking
    current_phase: str = "init"
    completed_phases: list[str] = Field(default_factory=list)
    phase_results: dict[str, Any] = Field(default_factory=dict)
    plan: dict[str, Any] | None = None

    # Intelligence accumulation
    entity_graph_snapshot: dict[str, Any] = Field(default_factory=dict)
    findings: list[dict[str, Any]] = Field(default_factory=list)
    phishing_package: dict[str, Any] = Field(default_factory=dict)
    cloud_intel: dict[str, Any] = Field(default_factory=dict)
    code_intel: dict[str, Any] = Field(default_factory=dict)
    identity_intel: dict[str, Any] = Field(default_factory=dict)
    vuln_intel: dict[str, Any] = Field(default_factory=dict)

    # Hypotheses / leads generated by correlation agent
    open_hypotheses: list[str] = Field(default_factory=list)
    confirmed_leads: list[str] = Field(default_factory=list)

    # Budget tracking
    llm_cost_usd: float = 0.0
    tool_cost_usd: float = 0.0
    api_calls: int = 0
    step_count: int = 0

    # Errors and notes
    errors: list[str] = Field(default_factory=list)
    reflection_notes: list[str] = Field(default_factory=list)
    agent_messages: list[dict[str, Any]] = Field(default_factory=list)

    # Timestamps
    started_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Report output paths (set after generation)
    report_paths: dict[str, str] = Field(default_factory=dict)

    def touch(self) -> None:
        self.updated_at = datetime.utcnow()

    def add_finding(self, finding_dict: dict[str, Any]) -> None:
        self.findings.append(finding_dict)
        self.touch()

    def mark_phase_complete(self, phase_name: str) -> None:
        if phase_name not in self.completed_phases:
            self.completed_phases.append(phase_name)
        self.current_phase = phase_name
        self.touch()

    def total_cost_usd(self) -> float:
        return self.llm_cost_usd + self.tool_cost_usd
