"""Cobalt Strike Malleable C2 profile stub emitter.

Cobalt Strike's Malleable C2 profiles are a domain-specific
language for shaping how a Beacon's network traffic looks.
A full profile is operator tradecraft and out of scope here.
What we CAN auto-fill is the pretext-derived header
boilerplate — user-agent strings, header lists, hostnames
the operator gathered during recon — so the operator starts
from a campaign-specific stub instead of a generic template.

What we emit
- A ``.profile`` file with:
  * Comments documenting which NexusRecon entities seeded
    which fields.
  * A ``set sample_name`` referencing the campaign's lead
    target.
  * A list of ``set useragent`` candidates derived from any
    Technology entities the campaign observed (e.g. "Apache
    2.4.x" → a plausible mobile/desktop UA matching that
    server's typical client mix).
  * ``http-get { ... }`` and ``http-post { ... }`` skeletons
    with the campaign's confirmed subdomains listed as
    candidate ``set uri`` values.

The output is INTENTIONALLY incomplete — the operator MUST
review and tune before deploying. Cobalt Strike's
documentation calls this profile shape ``"malleable-c2"``;
our stub is just a head-start.

What we deliberately don't auto-fill
- Process injection / sleep masking / data jitter — that's
  tradecraft.
- Encryption keys / pipe names — operator-specific.
- ``stage`` / ``post-ex`` blocks — out of scope for OSINT
  output.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any


_DEFAULT_USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
    '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 '
    '(KHTML, like Gecko) Version/17.0 Safari/605.1.15',
    'Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0',
]


def emit_cobaltstrike_profile_stub(
    graph: Any,
    out_path: Path | str,
    *,
    profile_name: str = "nexusrecon-stub",
    sample_target: str | None = None,
) -> Path:
    """Write a Malleable C2 profile stub seeded by ``graph``.

    Operators MUST review + tune before deploying — see the
    module docstring. The ``sample_target`` argument lets the
    caller pin the headline domain; if omitted we pick the
    first ``domain`` entity in the graph."""

    out = Path(out_path).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)

    # Pick the headline target.
    domains = sorted(
        d["value"] for _, d in graph.graph.nodes(data=True)
        if d.get("entity_type") == "domain"
    )
    if sample_target is None:
        sample_target = domains[0] if domains else "example.com"

    subdomains = sorted(
        d["value"] for _, d in graph.graph.nodes(data=True)
        if d.get("entity_type") == "subdomain"
    )
    technologies = sorted(
        d["value"] for _, d in graph.graph.nodes(data=True)
        if d.get("entity_type") == "technology"
    )

    lines: list[str] = [
        "# Malleable C2 profile stub — generated by NexusRecon.",
        "# Operators MUST review + tune before deploying.",
        "# Tradecraft fields (sleep, jitter, post-ex, stage) are NOT auto-filled.",
        "",
        f'set sample_name "{profile_name}";',
        f'set pipename "{profile_name}_pipe_##_####";',
        "",
        "## Seeded from NexusRecon entities ##",
        f"# Headline target:      {sample_target}",
        f"# Subdomains discovered: {len(subdomains)}",
        f"# Technologies observed: "
        f"{', '.join(technologies) if technologies else '(none)'}",
        "",
        "http-config {",
        "    set trust_x_forwarded_for \"true\";",
        '    header "Server" "nginx";',
        "}",
        "",
        "http-get {",
        f'    set uri "{_default_uris(subdomains)}";',
        "    client {",
    ]
    for ua in _DEFAULT_USER_AGENTS:
        lines.append(f'        header "User-Agent" "{ua}";')
    lines.extend([
        '        header "Accept" "text/html,application/xhtml+xml,*/*;q=0.8";',
        '        header "Accept-Language" "en-US,en;q=0.9";',
        '        metadata {',
        '            base64url;',
        '            parameter "session";',
        '        }',
        "    }",
        "    server {",
        '        header "Content-Type" "text/html; charset=utf-8";',
        '        output {',
        '            base64url;',
        '            print;',
        '        }',
        "    }",
        "}",
        "",
        "http-post {",
        f'    set uri "{_default_post_uris(subdomains)}";',
        "    client {",
    ])
    for ua in _DEFAULT_USER_AGENTS:
        lines.append(f'        header "User-Agent" "{ua}";')
    lines.extend([
        '        header "Content-Type" "application/x-www-form-urlencoded";',
        '        id {',
        '            base64url;',
        '            parameter "id";',
        '        }',
        '        output {',
        '            base64url;',
        '            print;',
        '        }',
        "    }",
        "    server {",
        '        header "Content-Type" "text/plain";',
        '        output {',
        '            base64url;',
        '            print;',
        '        }',
        "    }",
        "}",
        "",
        "# End of stub. Tune sleep_time, jitter, and post-ex blocks before deploying.",
    ])
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def _default_uris(subdomains: list[str]) -> str:
    """Pick a few plausible ``set uri`` candidates from the
    operator's recon. If we have subdomains the operator's
    real targets came up under, mimic their patterns. Else
    fall back to generic web-app paths."""
    if not subdomains:
        return "/api/v1/status /assets/images /search?q=1"
    # Just borrow the subdomain root paths.
    candidates = [f"/{s.split('.', 1)[0]}/status" for s in subdomains[:3]]
    return " ".join(candidates)


def _default_post_uris(subdomains: list[str]) -> str:
    if not subdomains:
        return "/api/v1/submit /auth/login /events"
    candidates = [f"/{s.split('.', 1)[0]}/submit" for s in subdomains[:3]]
    return " ".join(candidates)
