"""WAF detection via response signature matching."""
from __future__ import annotations

from typing import Any, Dict, List

import httpx

from nexusrecon.tools.base import Category, OSINTTool, Tier, ToolResult
from nexusrecon.tools.registry import register_tool

_HEADERS_BENIGN = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0",
    "Accept": "text/html",
}

WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "header_patterns": [("server", "cloudflare"), ("cf-ray", None)],
        "body_patterns": ["cloudflare ray id", "cloudflare-nginx", "checking your browser"],
        "status_codes": [],
    },
    {
        "name": "AWS WAF",
        "header_patterns": [("x-amzn-requestid", None), ("x-amz-cf-id", None)],
        "body_patterns": ["aws.amazon.com/waf", "<error>access denied</error>"],
        "status_codes": [403],
    },
    {
        "name": "Akamai",
        "header_patterns": [("x-check-cacheable", None), ("akamai-grn", None)],
        "body_patterns": ["access denied", "reference #", "akamai"],
        "status_codes": [403],
    },
    {
        "name": "Imperva / Incapsula",
        "header_patterns": [("x-iinfo", None), ("x-cdn", "incapsula")],
        "body_patterns": ["incapsula incident id", "powered by incapsula", "_Incapsula_Resource"],
        "status_codes": [],
    },
    {
        "name": "Sucuri",
        "header_patterns": [("x-sucuri-id", None), ("x-sucuri-cache", None)],
        "body_patterns": ["sucuri webwall", "cloudproxy"],
        "status_codes": [403],
    },
    {
        "name": "F5 BIG-IP ASM",
        "header_patterns": [("x-cnection", None), ("set-cookie", "TS0")],
        "body_patterns": ["the requested url was rejected", "your support id is"],
        "status_codes": [403, 406],
    },
    {
        "name": "ModSecurity",
        "header_patterns": [("server", "mod_security"), ("server", "modsec")],
        "body_patterns": ["not acceptable!", "406 not acceptable", "mod_security"],
        "status_codes": [406],
    },
    {
        "name": "Wordfence",
        "header_patterns": [],
        "body_patterns": ["generated by wordfence", "your access to this site has been limited", "wordfence"],
        "status_codes": [403],
    },
    {
        "name": "Barracuda",
        "header_patterns": [("set-cookie", "barra_counter_session")],
        "body_patterns": ["barracuda networks", "you are seeing this page because the site you were trying to visit has blocked your access"],
        "status_codes": [403],
    },
    {
        "name": "Fastly",
        "header_patterns": [("x-fastly-request-id", None), ("fastly-restarts", None)],
        "body_patterns": ["fastly error", "via fastly"],
        "status_codes": [],
    },
]


def _score_waf(waf: Dict[str, Any], headers: Dict[str, str], body: str, status: int) -> float:
    score = 0.0
    body_lower = body.lower()[:5000]

    for header_name, header_value in waf["header_patterns"]:
        hval = headers.get(header_name, "").lower()
        if hval:
            if header_value is None or header_value.lower() in hval:
                score += 0.4

    for pattern in waf["body_patterns"]:
        if pattern.lower() in body_lower:
            score += 0.3

    if waf["status_codes"] and status in waf["status_codes"]:
        score += 0.2

    return min(score, 1.0)


@register_tool
class WafW00fTool(OSINTTool):
    name = "wafw00f"
    tier = Tier.T1
    category = Category.WEB
    requires_keys = []
    description = "Detect WAF presence and fingerprint provider via HTTP response signatures"
    target_types = ["domain"]

    async def run(self, target: str, **kwargs: Any) -> ToolResult:
        wafs_detected: List[Dict[str, Any]] = []

        try:
            async with httpx.AsyncClient(headers=dict(_HEADERS_BENIGN), timeout=15.0, follow_redirects=True) as client:
                # Benign probe
                try:
                    benign = await client.get(f"https://{target}/")
                    benign_headers = dict(benign.headers)
                    benign_body = benign.text
                    benign_status = benign.status_code
                except Exception:
                    benign_headers = {}
                    benign_body = ""
                    benign_status = 0

                # Malicious probe (XSS payload — triggers WAF block response)
                malicious_headers = dict(_HEADERS_BENIGN)
                try:
                    mal = await client.get(
                        f"https://{target}/?q=%3Cscript%3Ealert%281%29%3C%2Fscript%3E",
                        headers=malicious_headers,
                    )
                    mal_headers = dict(mal.headers)
                    mal_body = mal.text
                    mal_status = mal.status_code
                except Exception:
                    mal_headers = benign_headers
                    mal_body = benign_body
                    mal_status = benign_status

        except Exception as exc:
            return ToolResult(success=False, source=self.name, error=str(exc))

        for waf in WAF_SIGNATURES:
            # Check both benign and malicious response
            score = max(
                _score_waf(waf, benign_headers, benign_body, benign_status),
                _score_waf(waf, mal_headers, mal_body, mal_status),
            )
            if score >= 0.3:
                evidence_parts = []
                for hname, hval in waf["header_patterns"]:
                    hv = benign_headers.get(hname, "") or mal_headers.get(hname, "")
                    if hv:
                        evidence_parts.append(f"header:{hname}={hv[:50]}")
                for pat in waf["body_patterns"]:
                    if pat.lower() in (benign_body + mal_body).lower():
                        evidence_parts.append(f"body:{pat}")
                wafs_detected.append({
                    "name": waf["name"],
                    "confidence": round(score, 2),
                    "evidence": "; ".join(evidence_parts[:3]),
                })

        return ToolResult(
            success=True,
            source=self.name,
            data={"target": target, "wafs_detected": wafs_detected},
            result_count=len(wafs_detected),
        )
